version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,EXTERNAL://localhost:9092  # Важно, чтобы EXTERNAL был привязан к порту 9092 на хосте
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092   # Настроить правильные порты для контейнера
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENER_NAMES: INSIDE,EXTERNAL
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - "9092:9092"  # Порты для подключения извне
      - "9093:9093"  # Порты для внутренней сети
    depends_on:
      - zookeeper
    networks:
      - kafka-net
  # Delete if there is an smtp server ...
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP-порт для отправки почты
      - "8025:8025"  # Веб-интерфейс для просмотра писем
    networks:
      - kafka-net
  nestjs:
    build: ./  # Укажи путь к проекту NestJS
    container_name: nestjs
    ports:
      - "3000:3000"  # Указываем порт, на котором будет работать приложение
    depends_on:
      - kafka  # NestJS зависит от Kafka
      - mailhog  # NestJS зависит от Mailhog
    environment:
      - KAFKA_BROKER=kafka:9093  # Указываем брокер Kafka
    networks:
      - kafka-net
networks:
  kafka-net:
    driver: bridge
